packages:
- .
extra-deps:
- git: https://github.com/davidsd/hyperion.git
  commit: d7d2484dc208cf4b15a98d0a9e504eb2858316bd
- git: https://gitlab.com/davidsd/hyperion-util.git
  commit: f8d99c7e89ca52728f76fa3890974773e7ea63b4
resolver: github:pkravchuk/hyperionage:snapshots/hyp-2.0.0.yaml
flags:
  crypton:
    use_target_attributes: false
arch: x86_64